import React, { useRef } from "react"
import type { NextPage } from 'next'
import slackeyFontImg from "./screenshots/Title/Rock-paper-scissors.png"
import Buttons from '../UI/telegram/TelegramButton'
import Head from "next/head"
import WalletButton from "../UI/wallet/WalletButton"
import playButton from "./screenshots/1920-1680px/play.png"

const Home: NextPage = () => {
  const circlesRef = useRef(null)
  return (
    <div>
      <Head>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link rel="icon" href="/favicon.ico" type="image/x-icon" sizes="any" />
      </Head>

      <div className="App">
        <header className="App-header">
          <img src={slackeyFontImg.src} className="SlackeyFontImg" alt="" />
          <p> Сonnect your Telegram to start the game </p>
          <div ref={circlesRef} className='circles'>
            <div></div>
            <div></div>
            <div></div>
          </div>
          <a className="playButton" href="tg://resolve?domain=YetAnotherRoshamBot"> <img src={playButton.src} alt="" /> </a>

          <WalletButton />

          <Buttons />
        </header>
      </div>
    </div>
  )
}

export default Home
