import React, { useRef, useState } from "react"
import type { NextPage } from 'next'
import slackeyFontImg from "./screenshots/Title/Rock-paper-scissors.png"
import Buttons from '../components/Buttons'
import Head from "next/head"

interface IBooleanSteps {
  second: boolean;
  third: boolean;
}

const Home: NextPage = () => {
  const [booleanSteps, setBooleanSteps] = useState<IBooleanSteps>({ second: false, third: false })

  const circlesRef = useRef(null)
  return (
    <div>
      <Head>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link rel="icon" href="/favicon.ico" type="image/x-icon" sizes="any" />
      </Head>

      <div className="App">
        <header className="App-header">
          <img src={slackeyFontImg.src} className="SlackeyFontImg" alt="" />
          <p> Сonnect your Telegram to start the game </p>

          <div ref={circlesRef} className='steps'>

            <div style={{ backgroundColor: "#ffbc48" }}></div>

            {booleanSteps.second
              ? <div style={{ background: "#ffbc48" }}></div>
              : <div style={{ background: "#a0592a" }}></div>

            }
            {booleanSteps.third
              ? <div style={{ backgroundColor: "#ffbc48" }}></div>
              : <div style={{ backgroundColor: "#a0592a" }}></div>
            }
          </div>

          <Buttons setBooleanSteps={setBooleanSteps} />
        </header>
      </div>
    </div>
  )
}

export default Home
